apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mealiedeploy
  name: mealiedeploy
  namespace: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealiedeploy
  template:
    metadata:
      labels:
        app: mealiedeploy
    spec:
      containers:
        - image: ghcr.io/mealie-recipes/mealie:v1.2.0
          name: mealie
          ports:
            - containerPort: 9000
          volumeMounts:
            - mountPath: /app/data
              name: mealie-data
      volumes:
       - name: mealie-data
         persistentVolumeClaim:
           claimName: mealie-data
